config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admins', as: 'rails_admin'

  resources :comments
  post 'report_comment' => 'comments#report_comment', as: :report_comment

  resources :posts, except: :show
  get 'show_comments' => 'posts#show_comments', as: :show_comments
  get 'hide_comments' => 'posts#hide_comments', as: :hide_comments
  post 'report_post' => 'posts#report_post', as: :report_post

  get '/change_locale/:locale', to: 'settings#change_locale', as: :change_locale

  resources 'contacts', only: [:new, :create]

  devise_for :users

  resources :users
  get 'like' => 'users#like'
  get 'unlike' => 'users#unlike'

  root 'home#index'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/comment.rb
class Comment < ActiveRecord::Base

  belongs_to :post
  belongs_to :user

  has_many :hidden_comments
  has_many :users, through: :hidden_comments

  acts_as_likeable

  validates :content, presence: true, allow_blank: false

  auto_html_for :content do
    html_escape
    image
    youtube
    link :target => '_blank', :rel => 'nofollow'
    simple_format
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  respond_to :js

  def create
    @post = Post.find(params[:comment][:post_id])
    @comment = Comment.new(params[:comment].permit(:content, :content_html, :post_id),
                           content_html: Obscenity.sanitize(params[:comment][:content]))
    @comment.user_id = current_user.id if current_user
    @comment.save
    respond_with(@comment)
  end

  def report_comment
    @comment = Comment.find(params[:id])
    hc = HiddenComment.new(user_id: current_user.id, comment_id: @comment.id)
    hc.save

    # below: if three combined comments and posts from user are equal 3 or more, this user will be hidden for current_user
    if @comment.user_id and ((HiddenPost.where(user_id: current_user.id).where(post_id: Post.where(user_id: @comment.user_id).ids)
                                  .size+HiddenComment.where(user_id: current_user.id)
                                            .where(comment_id: Comment.where(user_id: @comment.user_id).ids).size) >= 3)
      hu = HiddenUser.new(user_id: current_user.id, hidden_user_id: @comment.user_id)
      hu.save

      if HiddenUser.where(hidden_user_id: @comment.user_id).size >= 3
        bu = User.find(@comment.user_id)
        bu.banned = true
        bu.save
      end
    end

    if HiddenComment.where(comment_id: @comment.id).size >= 3
      @comment.hidden=true
      @comment.save
    end
  end

end

app/helpers/comments_helper.rb
module CommentsHelper

  def check_if_comment_cannot_be_seen(comment)
    if current_user
      if comment.user_id
        comment.hidden or
            User.find(comment.user_id).banned? or
            HiddenUser.where(hidden_user_id: comment.user_id).where(user_id: current_user.id).size > 0 or
            HiddenComment.where(user_id: current_user.id).where(comment_id: comment.id).size > 0
      else
        comment.hidden or
            HiddenComment.where(user_id: current_user.id).where(comment_id: comment.id).size > 0
      end
    else
      if comment.user_id
        comment.hidden or User.find(comment.user_id).banned?
      else
        comment.hidden
      end
    end
  end

end

app/views/comments/_comment.html.haml
%hr
.comment{id: "#{comment.class}-#{comment.id}"}
  - if comment and (check_if_comment_cannot_be_seen(comment) == false)
    .date
    %i.glyphicon.glyphicon-time
    = comment.created_at.strftime('%d-%m-%Y')
    - if current_user and !(comment.user_id and comment.user_id == current_user.id)
      = link_to report_comment_path(id: comment.id), method: :post, remote: true, data: { confirm: I18n.t('are_you_sure_to_report_comment') } do
        %i.glyphicon.glyphicon-flag
    - if @post.user_id
      %i.glyphicon.glyphicon-user{title: I18n.t('posts.created_logged')}
    %div
      %br
      = comment.content_html
    %div{class: "#{comment.class}-#{comment.id}"}
      = render 'shared/like_form', likeable: comment
      .likes
        %i.glyphicon.glyphicon-heart
        = comment.likers(User).count
  - else
    %div
      = I18n.t('posts.keep_reading')

app/views/comments/create.js.haml
$(document.getElementById('comments-#{@post.id}')).append('#{j render(@comment)}');
$('#submit-#{@post.id}').val('');
$('#link_to-#{@post.id}').load(document.URL + ' #link_to-#{@post.id}');

var container = document.querySelector('#masonry');
var msnry = new Masonry(container, {
columnWidth: '.post',
itemSelector: '.post'
});

imagesLoaded(container, function () {
msnry = new Masonry(container);
});

app/views/comments/report_comment.js.haml
-#$(document.getElementById('#{@comment.class}-#{@comment.id}')).val('#{I18n.t('posts.keep_reading')}').italics();
var element = document.getElementById('#{@comment.class}-#{@comment.id}').getElementsByTagName('div');
element[1].innerHTML = ('#{I18n.t('posts.keep_reading')}').italics();
element[0].remove();
element[2].remove();

var container = document.querySelector('#masonry');
var msnry = new Masonry(container, {
columnWidth: '.post',
itemSelector: '.post'
});

imagesLoaded(container, function () {
msnry = new Masonry(container);
});