config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admins', as: 'rails_admin'

  resources :comments
  post 'report_comment' => 'comments#report_comment', as: :report_comment

  resources :posts, except: :show
  get 'show_comments' => 'posts#show_comments', as: :show_comments
  get 'hide_comments' => 'posts#hide_comments', as: :hide_comments
  post 'report_post' => 'posts#report_post', as: :report_post

  get '/change_locale/:locale', to: 'settings#change_locale', as: :change_locale

  resources 'contacts', only: [:new, :create]

  devise_for :users

  resources :users
  get 'like' => 'users#like'
  get 'unlike' => 'users#unlike'

  root 'home#index'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/views/shared/_form.html.haml
- if (current_user and !current_user.banned and !current_user.admin) || (!current_user and !@post.user_id)
  = form_for @comment, remote: true do |f|
    - if @comment.errors.any?
      #error_explanation
        %h2
          = pluralize(@comment.errors.count, 'error')
          prohibited this post from being saved:
        %ul
          - @comment.errors.full_messages.each do |msg|
            %li= msg
    = f.hidden_field :post_id, value: @post.id
    .form-group#comment-textarea
      = f.text_area :content, :id => "submit-#{@post.id}", placeholder: t('posts.content')
    .actions#comment-form
      = f.submit t('posts.share'), class: 'btn btn-primary'

app/views/shared/_like.html.haml
= link_to like_path(likeable_id: likeable.id, likeable_type: likeable.class), method: :get, remote: true, class: 'like' do
  %i.glyphicon.glyphicon-heart-empty
  = I18n.t('posts.like').capitalize

app/views/shared/_like_form.html.haml
- if current_user and !current_user.banned and !current_user.admin
  #like_form
    - if current_user.likes?(likeable)
      = render 'shared/unlike', likeable: likeable
    - else
      = render 'shared/like', likeable: likeable

app/views/shared/_unlike.html.haml
= link_to unlike_path(likeable_id: likeable.id, likeable_type: likeable.class), method: :get, remote: true, class: 'unlike' do
  %i.glyphicon.glyphicon-heart
  = I18n.t('posts.unlike').capitalize