config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admins', as: 'rails_admin'

  resources :comments
  post 'report_comment' => 'comments#report_comment', as: :report_comment

  resources :posts, except: :show
  get 'show_comments' => 'posts#show_comments', as: :show_comments
  get 'hide_comments' => 'posts#hide_comments', as: :hide_comments
  post 'report_post' => 'posts#report_post', as: :report_post

  get '/change_locale/:locale', to: 'settings#change_locale', as: :change_locale

  resources 'contacts', only: [:new, :create]

  devise_for :users

  resources :users
  get 'like' => 'users#like'
  get 'unlike' => 'users#unlike'

  root 'home#index'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/post.rb
class Post < ActiveRecord::Base

  belongs_to :user
  has_many :comments, dependent: :destroy

  has_many :hidden_posts
  has_many :users, through: :hidden_posts

  as_enum :category, everyday_life: 1, dreams_and_hopes: 2, regrets: 3, thoughts: 4, other: 5

  acts_as_likeable

  validates :content, presence: {message: I18n.t('posts.cannot_be_blank')}, allow_blank: false

  attachment :image_content, type: :image

  auto_html_for :content do
    html_escape
    image
    youtube
    # twitter
    link :target => '_blank', :rel => 'nofollow'
    simple_format
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  respond_to :js, :html

  skip_before_filter :verify_authenticity_token, :only => [:create] # for image upload and AJAX

  # GET /posts
  # GET /posts.json
  def index
    # console
    new # for rendering new_post in index
    page = params[:page] ? params[:page] : 1
    category = params[:category].to_i if params[:category] and params[:category] != '0'
    if category == -1
      @posts = Post.where(user_id: current_user.id).order('created_at desc').page(page)
    else
      if category
        @posts = Post.where(category_cd: category)
                     .where.not(user_id: User.where(banned: true).ids)
                     .where.not(hidden: true)
      else
        @posts = Post.where.not(user_id: User.where(banned: true).ids)
                     .where.not(hidden: true)
      end
      if current_user and current_user.show_all
        @posts = @posts.where.not(user_id: User.where(banned: true).ids) # not banned
                     .where.not(id: current_user.hidden_posts.pluck(:post_id)) # not hidden as post
                     .order('created_at desc').page(page)
      elsif current_user and !current_user.show_all
        @posts = @posts.where.not(user_id: nil) #not anonymous
                     .where.not(user_id: HiddenUser.where(user_id: current_user.id).pluck(:hidden_user_id))
                     .where.not(id: current_user.hidden_posts.pluck(:post_id))
                     .order('created_at desc').page(page)
      else
        @posts = @posts.order('created_at desc').page(page)
      end
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @comment = Comment.new
    @post = Post.find(params[:id])
    @comments = @post.comments.order('created_at asc')
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params, content_html: Obscenity.sanitize(post_params[:content]))
    @post.user_id = current_user.id if current_user
    if params[:category] and params[:category] != '' and params[:category] != '0'
      @post.category = params[:category].to_i
    else
      @post.category = 5
    end
    @post.save
    respond_to do |format|
      format.html { redirect_to :back }
      format.js
    end
  end

  def update
    @post.update(post_params)
    respond_with(@post)
  end

  def destroy
    @post.destroy
    respond_with(@post)
  end

  def show_comments
    @comment = Comment.new
    @post = Post.find(params[:id])
    @comments = @post.comments.order('created_at asc')
  end

  def hide_comments
    @post = Post.find(params[:id])
  end

  def report_post
    @post = Post.find(params[:id])
    hp = HiddenPost.new(user_id: current_user.id, post_id: @post.id)
    hp.save

    # below: if three combined comments and posts from user are equal 3 or more, this user will be hidden for current_user
    if @post.user_id and ((HiddenPost.where(user_id: current_user.id).where(post_id: Post.where(user_id: @post.user_id).ids)
                               .size+HiddenComment.where(user_id: current_user.id)
                                                                    .where(comment_id: Comment.where(user_id: @post.user_id).ids).size) >= 3)
      hu = HiddenUser.new(user_id: current_user.id, hidden_user_id: @post.user_id)
      hu.save

      if HiddenUser.where(hidden_user_id: @post.user_id).size >= 3
        bu = User.find(@post.user_id)
        bu.banned = true
        bu.save
      end
    end

    # to hide globally (for all users)
    if HiddenPost.where(post_id: @post.id).size >= 3
      @post.hidden=true
      @post.save
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_post
    @post = Post.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def post_params
    params.require(:post).permit(:content, :image_content, :content_html, :user_id)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_categories.html.haml
%ul.nav.nav-tabs.nav-justified
  - if params[:category] == '0' or params[:category].nil?
    %li.active.disabled
      = link_to (t('categories.all')), posts_path(category: 0)
    %li
      = link_to (t('enums.category.everyday_life')), posts_path(category: 1)
    %li
      = link_to (t('enums.category.dreams_and_hopes')), posts_path(category: 2)
    %li
      = link_to (t('enums.category.regrets')), posts_path(category: 3)
    %li
      = link_to (t('enums.category.thoughts')), posts_path(category: 4)
    %li
      = link_to (t('enums.category.other')), posts_path(category: 5)
    - if current_user and !current_user.admin
      %li
        = link_to (t('posts.my_posts')), posts_path(category: -1)
  - elsif params[:category] == '1'
    %li
      = link_to (t('categories.all')), posts_path(category: 0)
    %li.active
      = link_to (t('enums.category.everyday_life')), posts_path(category: 1)
    %li
      = link_to (t('enums.category.dreams_and_hopes')), posts_path(category: 2)
    %li
      = link_to (t('enums.category.regrets')), posts_path(category: 3)
    %li
      = link_to (t('enums.category.thoughts')), posts_path(category: 4)
    %li
      = link_to (t('enums.category.other')), posts_path(category: 5)
    - if current_user and !current_user.admin
      %li
        = link_to (t('posts.my_posts')), posts_path(category: -1)
  - elsif params[:category] == '2'
    %li
      = link_to (t('categories.all')), posts_path(category: 0)
    %li
      = link_to (t('enums.category.everyday_life')), posts_path(category: 1)
    %li.active
      = link_to (t('enums.category.dreams_and_hopes')), posts_path(category: 2)
    %li
      = link_to (t('enums.category.regrets')), posts_path(category: 3)
    %li
      = link_to (t('enums.category.thoughts')), posts_path(category: 4)
    %li
      = link_to (t('enums.category.other')), posts_path(category: 5)
    - if current_user and !current_user.admin
      %li
        = link_to (t('posts.my_posts')), posts_path(category: -1)
  - elsif params[:category] == '3'
    %li
      = link_to (t('categories.all')), posts_path(category: 0)
    %li
      = link_to (t('enums.category.everyday_life')), posts_path(category: 1)
    %li
      = link_to (t('enums.category.dreams_and_hopes')), posts_path(category: 2)
    %li.active
      = link_to (t('enums.category.regrets')), posts_path(category: 3)
    %li
      = link_to (t('enums.category.thoughts')), posts_path(category: 4)
    %li
      = link_to (t('enums.category.other')), posts_path(category: 5)
    - if current_user and !current_user.admin
      %li
        = link_to (t('posts.my_posts')), posts_path(category: -1)
  - elsif params[:category] == '4'
    %li
      = link_to (t('categories.all')), posts_path(category: 0)
    %li
      = link_to (t('enums.category.everyday_life')), posts_path(category: 1)
    %li
      = link_to (t('enums.category.dreams_and_hopes')), posts_path(category: 2)
    %li
      = link_to (t('enums.category.regrets')), posts_path(category: 3)
    %li.active
      = link_to (t('enums.category.thoughts')), posts_path(category: 4)
    %li
      = link_to (t('enums.category.other')), posts_path(category: 5)
    - if current_user and !current_user.admin
      %li
        = link_to (t('posts.my_posts')), posts_path(category: -1)
  - elsif params[:category] == '5'
    %li
      = link_to (t('categories.all')), posts_path(category: 0)
    %li
      = link_to (t('enums.category.everyday_life')), posts_path(category: 1)
    %li
      = link_to (t('enums.category.dreams_and_hopes')), posts_path(category: 2)
    %li
      = link_to (t('enums.category.regrets')), posts_path(category: 3)
    %li
      = link_to (t('enums.category.thoughts')), posts_path(category: 4)
    %li.active
      = link_to (t('enums.category.other')), posts_path(category: 5)
    - if current_user and !current_user.admin
      %li
        = link_to (t('posts.my_posts')), posts_path(category: -1)
  - elsif params[:category] == '-1'
    %li
      = link_to (t('categories.all')), posts_path(category: 0)
    %li
      = link_to (t('enums.category.everyday_life')), posts_path(category: 1)
    %li
      = link_to (t('enums.category.dreams_and_hopes')), posts_path(category: 2)
    %li
      = link_to (t('enums.category.regrets')), posts_path(category: 3)
    %li
      = link_to (t('enums.category.thoughts')), posts_path(category: 4)
    %li
      = link_to (t('enums.category.other')), posts_path(category: 5)
    - if current_user and !current_user.admin
      %li.active
        = link_to (t('posts.my_posts')), posts_path(category: -1)

app/views/posts/_comment_partial.html.haml
.comments{:id => "comments-#{@post.id}"}
  %br
  .show-comments
    = link_to (t('posts.hide_comments')), hide_comments_path(id: @post.id), remote: true, data: {id: @post.id}
  = render 'shared/form'
  = render @comments

app/views/posts/_form.html.haml
= form_for @post, remote: :true do |f|
  - if @post.errors.any?
    #error_explanation
      %h2= t 'date.errors.template.header.one', count: pluralize(@post.errors.count, 'error'), model: (t 'activerecord.attributes.post.post_name').downcase
      %ul
        - @post.errors.full_messages.each do |msg|
          %li= msg

  = hidden_field_tag(:category, params[:category])
  .form-control
    = f.text_area :content, :id => 'submit-new-post', placeholder: t('posts.content')
  .field#attachment_field
    = f.attachment_field :image_content, direct: true, class: 'filestyle', 'data-buttonName': 'btn-primary', 'data-iconName': 'glyphicon-inbox', 'data-buttonBefore': 'true', 'data-buttonText': I18n.t('posts.upload_file')
  .actions#submit-post
    = f.submit t('posts.share'), class: 'btn btn-primary'

app/views/posts/_post.html.haml
.post{id: post.id}
  .date
    %i.glyphicon.glyphicon-time
    = post.created_at.strftime('%d-%m-%Y')
    - if (current_user and post.user_id == current_user.id) or current_user.try(:admin?)
      = link_to post, method: :delete, remote: true, data: { confirm: I18n.t('are_you_sure_to_destroy') } do
        %i.glyphicon.glyphicon-trash{title: I18n.t('posts.trash')}
    - elsif current_user and post.user_id != current_user.id
      = link_to report_post_path(id: post.id), method: :post, remote: true, data: { confirm: I18n.t('are_you_sure_to_report_post') } do
        %i.glyphicon.glyphicon-flag{title: I18n.t('posts.flag')}
    %i.glyphicon.glyphicon-tag
    = translate_enum post, :category
    - if post.user_id
      %i.glyphicon.glyphicon-user{title: I18n.t('posts.created_logged')}
  .content
    =post.content_html
  - if post.image_content_id
    =image_tag attachment_url(post, :image_content, :fill, 300, 300)
    %br
  %div{class: "#{post.class}-#{post.id}"}
    =render 'shared/like_form', likeable: post
    .likes
      %i.glyphicon.glyphicon-heart
      = post.likers(User).count
    .comments{id: "link_to-#{post.id}"}
      %i.glyphicon.glyphicon-comment
      = post.comments.count
    %div.show-comments{id: "link-show-#{post.id}"}
      =link_to (t('posts.show_comments')), show_comments_path(id: post.id), remote: true, data: {id: post.id}

app/views/posts/create.js.haml
$(document.getElementById('masonry')).prepend('#{j render(@post)}');
$(document.getElementById('submit-new-post')).val('');
$(document.getElementById('attachment_field').firstElementChild).val('null');

var container = document.querySelector('#masonry');
var msnry = new Masonry(container, {
columnWidth: '.post',
itemSelector: '.post'
});

imagesLoaded(container, function () {
msnry = new Masonry(container);
});

app/views/posts/destroy.js.haml
$(document.getElementById('#{@post.id}')).remove();

var container = document.querySelector('#masonry');
var msnry = new Masonry(container, {
columnWidth: '.post',
itemSelector: '.post'
});

imagesLoaded(container, function () {
msnry = new Masonry(container);
});

app/views/posts/edit.html.haml
%h1 Editing post

= render 'form'

= link_to 'Show', @post
\|
= link_to 'Back', posts_path

app/views/posts/hide_comments.js.haml
$(document.getElementById(#{@post.id})).children(".comments").remove();
document.getElementById('link-show-#{@post.id}').style.display = 'block';

var container = document.querySelector('#masonry');
var msnry = new Masonry(container, {
columnWidth: '.post',
itemSelector: '.post',
isAnimated: !Modernizr.csstransitions
});

imagesLoaded(container, function () {
msnry = new Masonry(container);
});

app/views/posts/index.html.haml
= render 'posts/categories'

%br

- if current_user and !current_user.banned and !current_user.admin
  = render 'form'
- elsif current_user and current_user.banned
  %p.label.label-info
    = I18n.t('ban_info')
- elsif current_user.try(:admin?)
  %p.label.label-info
    = I18n.t('admin_welcome')
    = link_to I18n.t('admin_panel_ign'), rails_admin_path
- else
  %p.label.label-info
    = t('not_logged_in')
  = render 'form'

#masonry.endless-page
  = render @posts
  %ul.pagination
    %li
      = link_to_next_page @posts, t('posts.more_posts'), remote: true, params: { category: params[:category] }

app/views/posts/index.js.haml
$("#{j render(@posts)}").appendTo($("#masonry"));

var container = document.querySelector('#masonry');
var msnry = new Masonry(container, {
columnWidth: '.post',
itemSelector: '.post',
isAnimated: !Modernizr.csstransitions
});

imagesLoaded(container, function () {
msnry = new Masonry(container);
});

- if @posts.last_page?
  $('.pagination').remove();
  $('#masonry').append("<ul class=\"pagination label label-info\"><li>#{I18n.t('posts.no_more_posts')}</li></ul>");
- else
  $('.pagination').remove();
  $('#masonry').append("<ul class=\"pagination\"><li>#{j link_to_next_page(@posts, t('posts.more_posts'), remote: true, params: { category: params[:category] })}</li></ul>");

app/views/posts/new.html.haml
%h1 New post

= render 'form'

= link_to 'Back', posts_path

app/views/posts/report_post.js.haml
$(document.getElementById('#{@post.id}')).remove();

var container = document.querySelector('#masonry');
var msnry = new Masonry(container, {
columnWidth: '.post',
itemSelector: '.post'
});

imagesLoaded(container, function () {
msnry = new Masonry(container);
});

app/views/posts/show.html.haml
= render 'posts/categories'

- if current_user and current_user.banned
  %p.label.label-info
    = I18n.t('ban_info')
- elsif current_user.try(:admin?)
  %p.label.label-info
    = I18n.t('admin_welcome')
    = link_to I18n.t('admin_panel_ign'), rails_admin_path
- else
  %p.label.label-info
    = t('not_logged_in')

= render @post

app/views/posts/show_comments.js.haml
$(document.getElementById(#{@post.id})).append('#{j render partial: 'comment_partial'}');
document.getElementById('link-show-#{@post.id}').style.display = 'none';

var container = document.querySelector('#masonry');
var msnry = new Masonry(container, {
columnWidth: '.post',
itemSelector: '.post',
isAnimated: !Modernizr.csstransitions
});

imagesLoaded(container, function () {
msnry = new Masonry(container);
});