config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admins', as: 'rails_admin'

  resources :comments
  post 'report_comment' => 'comments#report_comment', as: :report_comment

  resources :posts, except: :show
  get 'show_comments' => 'posts#show_comments', as: :show_comments
  get 'hide_comments' => 'posts#hide_comments', as: :hide_comments
  post 'report_post' => 'posts#report_post', as: :report_post

  get '/change_locale/:locale', to: 'settings#change_locale', as: :change_locale

  resources 'contacts', only: [:new, :create]

  devise_for :users

  resources :users
  get 'like' => 'users#like'
  get 'unlike' => 'users#unlike'

  root 'home#index'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{class: "alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}"}
      %button.close{'aria-hidden' => 'true', 'data-dismiss' => 'alert', type: 'button'} ×
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.haml
%navbar.navbar-default.navbar-fixed-top
  .container
    .navbar-header
      %button.navbar-toggle{'data-target' => '.navbar-collapse', 'data-toggle' => 'collapse', type: 'button'}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      - if !current_user
        = link_to root_path, class: 'navbar-brand' do
          %i.glyphicon.glyphicon-home
          = t 'home'
      - else
        = link_to posts_path, class: 'navbar-brand' do
          %i.glyphicon.glyphicon-home
          = t 'home'
    .collapse.navbar-collapse
      %ul.nav.navbar-nav
        = render 'layouts/navigation_links_left'
      %ul.nav.navbar-nav.navbar-right
        = render 'layouts/navigation_links_right'
        %ul.nav.navbar-nav
        %li.dropdown
          %a.dropdown-toggle{'data-toggle' => 'dropdown', href: '#'}
            %i.glyphicon.glyphicon-globe
            = t('language_change')
            %span.caret
          %ul.dropdown-menu{role: 'menu'}
            %li
              = link_to (t(:en_US, :scope => :languages)), change_locale_path(:en)
            %li
              = link_to (t(:pl, :scope => :languages)), change_locale_path(:pl)

app/views/layouts/_navigation_links_right.html.haml
- if !current_user
  %li
    = link_to (t 'session.sign_in'), new_user_session_path
  %li
    = link_to (t 'session.sign_up'), new_user_registration_path
- else
  %li
    = link_to (t 'session.sign_out'), destroy_user_session_path, method: :delete
- if current_user
  %li
    = link_to edit_user_path(current_user) do
      %i.glyphicon.glyphicon-cog
      = t 'settings'
%li
  = link_to new_contact_path do
    %i.glyphicon.glyphicon-envelope
    = t 'contact'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{content: 'text/html; charset=UTF-8', 'http-equiv' => 'Content-Type'}/
    %meta{content: 'width=device-width, initial-scale=1.0', name: 'viewport'}/
    %title= content_for?(:title) ? yield(:title) : 'Anonynet'
    %meta{content: "#{content_for?(:description) ? yield(:description) : 'Anonynet'}", name: 'description'}/
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = growlyflash_static_notices
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
    - if controller_name == 'home' and action_name == 'index'
      %body#body-with-background-image
    - else
      %body
    %header
      = render 'layouts/navigation'
    #main-container.container
      .row
        #content.col-md-14
          %main{role: 'main'}
            -#= render 'layouts/messages' # growlyflash handles this
            = yield
    %footer.footer
      .container.inline-block
        %br
        %div.text-muted
          @ 2015 Created by Bartosz Ignaczewski.
          = link_to I18n.t('linkedin'), 'https://www.linkedin.com/in/bartoszignaczewski'

          -#%a{:href => "https://nl.linkedin.com/pub/bartosz-ignaczewski/ab/95b/311", :style => "text-decoration:none;"}
          -#  %span{:style => "font: 80% Arial,sans-serif; color:#0783B6;"}
          -#    %img{:alt => "View Bartosz Ignaczewski's LinkedIn profile", :border => "0", :height => "15", :src => "https://static.licdn.com/scds/common/u/img/webpromo/btn_in_20x15.png", :style => "vertical-align:middle;", :width => "20"} &nbsp;View Bartosz Ignaczewski's profile